sidebar:
  - index
  - page1
  - page2

url: "https://mkreyesh.github.io" 
baseurl: "/DocTemplate" 

search_enabled: true
auto_page_title: true
version: false

remote_theme: zendesk/jekyll-theme-zendesk-garden@main

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    enable_dollar_delimiter: true