sidebar:
  - page1
  - page1

url: "https://mkreyesh.github.io" 
baseurl: "/DocTemplate" 

search_enabled: true
auto_page_title: true
version: false

remote_theme: zendesk/jekyll-theme-zendesk-garden@main

plugins:
  - jekyll-remote-theme

